### ISSUE TITLE
Refactor Main Menu

### ISSUE THREAD

**Issue by kyleyoung1121** [EECE3093C/team-project-wiitanks-Base-Game#30]
Bug Fix:
Game will not run if the game-setup scene is linked to the main menu.
These scenes can not link to one another, or it will cause a cyclic redundancy.

Action Needed:
Create a single menu handler and have it link between scenes appropriately.

**Comment by qtrunguyen** [comment]
A possible solution is using Singleton pattern. Singleton pattern is useful when there are some information you need to store persistently when switching scenes. 

Documentation for Singleton in Godot 4.0 can be found [here](https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html)

**Comment by kyleyoung1121** [comment]
Closing Issue: 
Scenes are now connected by path, not PackedScene.
Doing it this way avoids a cyclical redundancy that was scene when using a PackedScene
With this error resolved, the back button in the set_up_match.tscn has returned
